<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<InvariantGlobalization>true</InvariantGlobalization>
		<SelfContained>false</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishSingleFile>true</PublishSingleFile>
		<AssemblyTitle>Raccoongame</AssemblyTitle>
		<ApplicationIcon>autumn.ico</ApplicationIcon>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PublishTrimmed>False</PublishTrimmed>
		<PublishAot>False</PublishAot>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Raylib-cs" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<!-- Force dotnet to copy the native FMOD DLLs directly next to your game executable -->
		<None Include="NativeLibs/win-x64/fmodL.dll">
			<Link>fmodL.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="NativeLibs/win-x64/fmodstudioL.dll">
			<Link>fmodstudioL.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="NativeLibs/win-x64/fmod.dll">
			<Link>fmod.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="NativeLibs/win-x64/fmodstudio.dll">
			<Link>fmodstudio.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<!-- Automatically copy the entire Assets folder and its subdirectories to the build output -->
		<None Include="assets\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Content Include="autumn.ico" />

		<None Include="konfig.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
